

intranet_candidacies:
    path:     /candidatures
    defaults: { _controller: JobBundle:Intranet/Candidacy:index }


############# Society ################
intranet_societies:
    path:     /entreprises-partenaires
    defaults: { _controller: JobBundle:Intranet/Society:index }

intranet_society_view:
    path:     /entreprise/{society}/details
    defaults: { _controller: JobBundle:Intranet/Society:view }


intranet_society_create:
    path:     /entreprises-partenaires/nouvelle-entreprise
    defaults: { _controller: JobBundle:Intranet/Society:create }


intranet_society_update:
    path:     /entreprises-partenaires/modifier/{society}
    defaults: { _controller: JobBundle:Intranet/Society:update }


intranet_society_delete:
    path:     /entreprises-partenaires/supprimer/{society}
    defaults: { _controller: JobBundle:Intranet/Society:delete }


intranet_society_upload_logo:
    path:     /entreprises-partenaires/{society}/ajout-logo
    defaults: { _controller: JobBundle:Intranet/Society:addLogo }
    
    
############# Offres ################
intranet_offers:
    path:     /offres-de-poste
    defaults: { _controller: JobBundle:Intranet/Offer:index }

intranet_offer_view:
    path:     /offre/{offer}/details
    defaults: { _controller: JobBundle:Intranet/Offer:view }


intranet_offer_create:
    path:     /offres-de-poste/nouvelle-offre
    defaults: { _controller: JobBundle:Intranet/Offer:create }


intranet_offer_update:
    path:     /offres-de-poste/modifier/{offer}
    defaults: { _controller: JobBundle:Intranet/Offer:update }


intranet_offer_delete:
    path:     /offres-de-poste/supprimer/{offer}
    defaults: { _controller: JobBundle:Intranet/Offer:delete }

############# Skills ################
intranet_skills:
    path:     /administration/competences
    defaults: { _controller: JobBundle:Intranet/Skill:index }


# SkillType
intranet_skill_type_create:
    path:     /administration/type-competence/ajouter
    defaults: { _controller: JobBundle:Intranet/Skill:createType }

intranet_skill_type_view:
    path:     /administration/type-competence/{skillType}/details
    defaults: { _controller: JobBundle:Intranet/Skill:viewType }


intranet_skill_type_update:
    path:     /administration/type-competence/modifier/{skillType}
    defaults: { _controller: JobBundle:Intranet/Skill:updateType }


intranet_skill_type_delete:
    path:     /administration/type-competence/supprimer/{skillType}
    defaults: { _controller: JobBundle:Intranet/Skill:deleteType }


# Skill
intranet_skill_view:
    path:     /administration/competence/{skill}/details
    defaults: { _controller: JobBundle:Intranet/Skill:view }


intranet_skill_create:
    path:     /administration/competence/ajouter
    defaults: { _controller: JobBundle:Intranet/Skill:create }


intranet_skill_update:
    path:     /administration/competence/modifier/{skill}
    defaults: { _controller: JobBundle:Intranet/Skill:update }


intranet_skill_delete:
    path:     /administration/competence/supprimer/{skill}
    defaults: { _controller: JobBundle:Intranet/Skill:delete }

# cv
cv_index:
    path:     /cv/
    defaults: { _controller: JobBundle:Intranet/CV:index }

cv_new:
    path:     /cv/new
    defaults: { _controller: JobBundle:Intranet/CV:new }

cv_show:
    path:     /cv/{id}
    defaults: { _controller: JobBundle:Intranet/CV:show }

cv_edit:
    path:     /cv/{id}/edit
    defaults: { _controller: JobBundle:Intranet/CV:edit }

cv_delete:
    path:     /cv/{id}/delete
    defaults: { _controller: JobBundle:Intranet/CV:delete }
