

intranet_candidacies:
    path:     /candidatures
    defaults: { _controller: JobBundle:Intranet/Candidacy:index }


############# Society ################
intranet_societies:
    path:     /entreprises-partenaires
    defaults: { _controller: JobBundle:Intranet/Society:index }

intranet_society_view:
    path:     /entreprise/{society}/details
    defaults: { _controller: JobBundle:Intranet/Society:view }


intranet_society_create:
    path:     /entreprises-partenaires/nouvelle-entreprise
    defaults: { _controller: JobBundle:Intranet/Society:create }


intranet_society_update:
    path:     /entreprises-partenaires/modifier/{society}
    defaults: { _controller: JobBundle:Intranet/Society:update }


intranet_society_delete:
    path:     /entreprises-partenaires/supprimer/{society}
    defaults: { _controller: JobBundle:Intranet/Society:delete }


intranet_society_upload_logo:
    path:     /entreprises-partenaires/{society}/ajout-logo
    defaults: { _controller: JobBundle:Intranet/Society:addLogo }
    
    
############# Offres ################
intranet_offers:
    path:     /offres-de-poste
    defaults: { _controller: JobBundle:Intranet/Offer:index }

intranet_offer_view:
    path:     /offre/{offer}/details
    defaults: { _controller: JobBundle:Intranet/Offer:view }


intranet_offer_create:
    path:     /offres-de-poste/nouvelle-offre
    defaults: { _controller: JobBundle:Intranet/Offer:create }


intranet_offer_update:
    path:     /offres-de-poste/modifier/{offer}
    defaults: { _controller: JobBundle:Intranet/Offer:update }


intranet_offer_delete:
    path:     /offres-de-poste/supprimer/{offer}
    defaults: { _controller: JobBundle:Intranet/Offer:delete }
    