user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
ipssi:
    resource: "@IpssiBundle/Resources/config/routing.yml"
    prefix:   /

intranet:
    resource: "@IntranetBundle/Resources/config/routing.yml"
    prefix:   /intranet