intranet:
    resource: "@IntranetBundle/Resources/config/routing.yml"
    prefix:   /intranet

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

ipssi:
    resource: "@IpssiBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    

# Routing for Intranet
#back:
#    resource:   "@IpssiBundle/Controller/Back/"
#    prefix:     /intranet
#    type:       annotation

