user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

ipssi:
    resource: "@IpssiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"