user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

ipssi:
    resource: "@IpssiBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    

# Routing for Intranet
#back:
#    resource:   "@IpssiBundle/Controller/Back/"
#    prefix:     /intranet
#    type:       annotation

intranet:
    path:       /intranet
    defaults:   { _controller: "backend.backcontroller:indexAction" }