user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
ipssi:
    resource: "@IpssiBundle/Controller/"
    prefix:   /
    type: annotation

# Routing for Intranet
intranet:
    resource:   "@IpssiBundle/Controller/Backend/"
    prefix:     /intranet
    type:       annotation

intranet:
    path:       /intranet
    defaults:   { _controller: "backend.backcontroller:indexAction" }

intranet/page:
    path:       /intranet/page
    defaults:   { _controller: "backend.pagecontroller:indexAction" }