# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

imports:
    - { resource: "@UserBundle/Resources/config/security.yml" }

security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        UserBundle\Entity\User: bcrypt

            
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                # login success redirecting options (read further below)
                always_use_default_target_path: true
                default_target_path: /intranet
                #target_path_parameter:          _target_path
                #use_referer:                    false
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login
                always_use_default_target_path: true
                default_target_path: /intranet

                oauth_user_provider:
                    service: my_user_provider

            logout:       true
            anonymous:    true


    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
        
    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/intranet, role: ROLE_USER }
    - { path: ^/admin/, role: ROLE_ADMIN }