# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

imports:
    - { resource: "@UserBundle/Resources/config/security.yml" }

security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        UserBundle\Entity\User: bcrypt

            
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # login_path: /login
                # check_path: /login_check
                # login success redirecting options (read further below)
                # always_use_default_target_path: true
                default_target_path: /intranet
                #target_path_parameter:          _target_path
                #use_referer:                    false
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login
                always_use_default_target_path: true
                default_target_path: /intranet

                oauth_user_provider:
                    service: my_user_provider

            logout:       true
            anonymous:    true
            switch_user:  true


    role_hierarchy:
        ROLE_REDACTEUR: ROLE_USER, ROLE_ALL_NEWS, ROLE_ALL_PAGES
        ROLE_COLLABORATEUR: ROLE_USER, ROLE_VIEW_NEWS, ROLE_CREATE_EXPENSE, ROLE_CREATE_CRA, ROLE_CREATE_VACATION
        ROLE_RH: ROLE_USER, ROLE_ALL_USER, ROLE_ALL_CANDIDACY, ROLE_ALL_JOBOFFER, ROLE_ALL_CV, ROLE_ALL_EXPENSE, ROLE_ALL_CRA, ROLE_ALL_VACATION
        ROLE_MANAGER: ROLE_USER, ROLE_VIEW_USER, ROLE_EDIT_CANDIDACY, ROLE_VIEW_JOBOFFER, ROLE_EDIT_CV, ROLE_CREATE_EXPENSE, ROLE_EDIT_CRA, ROLE_EDIT_VACATION
        ROLE_SUPERVISEUR: ROLE_RH, ROLE_MANAGER

        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN, ROLE_REDACTEUR, ROLE_SUPERVISEUR , ROLE_ALLOWED_TO_SWITCH
        
    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/intranet, role: ROLE_USER }

# https://symfony.com/doc/3.1/security/voters.html
    access_decision_manager:
            strategy: affirmative