services:

    #-----------------------DATATABLES---------------------------------------------
    app.datatable.candidacy:
        class: Ipssi\JobBundle\Datatables\CandidacyDatatable
        parent: sg_datatables.datatable.abstract
