services:

    #-----------------------DATATABLES---------------------------------------------
    app.datatable.candidacy:
        class: Ipssi\JobBundle\Datatables\CandidacyDatatable
        parent: sg_datatables.datatable.abstract

    app.datatable.cv:
            class: Ipssi\JobBundle\Datatables\CVDatatable
            parent: sg_datatables.datatable.abstract
