offer_homepage:
    path:     /postes
    defaults: { _controller: JobBundle:App/Offer:index }

offer_show:
    path:     /postes/{slug}
    defaults: { _controller: JobBundle:App/Offer:show }

offer_candidate:
    path:     /postes/{slug}/postuler
    defaults: { _controller: JobBundle:App/Offer:candidate }