###################  Connexion ###########################
user_login:
    path:      /sign
    defaults:  { _controller: UserBundle:Security:login }

user_register:
    path:      /register
    defaults:   { _controller: UserBundle:Registration:register }


###################  Profil ###########################
user_profile:
    path:       /intranet/profil
    defaults:   { _controller: UserBundle:Profile:show }

user_contacts:
    path:       /intranet/profil/contacts
    defaults:   { _controller: UserBundle:Profile:showContacts }

user_profile_public:
    path:       /intranet/profil/{pseudo}
    defaults:   { _controller: UserBundle:Profile:publicProfile }
    options:
        expose: true

user_profile_edit:
    path:       /intranet/user/edit
    defaults:   { _controller: UserBundle:Profile:edit }


####################  Avatar ###########################
user_change_avatar:
    path:       /intranet/change-avatar
    defaults:   { _controller: UserBundle:Profile:changeAvatar }

user_upload_avatar:
    path:       /intranet/upload-avatar
    defaults:   { _controller: UserBundle:Profile:uploadAvatar }


###################  Newsletter ###########################
user_subscribe:
    path:       /intranet/subscribe
    defaults:   { _controller: UserBundle:Profile:subscribe }

user_unsubscribe:
    path:       /intranet/unsubscribe
    defaults:   { _controller: UserBundle:Profile:unsubscribe }