services:
    user.repository.user:
        class: UserBundle\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'UserBundle:User'
    user.repository.group:
        class: UserBundle\Repository\GroupRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'UserBundle:Group'
    my_user_provider:
        class: UserBundle\Security\Core\User\FOSUBUserProvider
        arguments: ['@fos_user.user_manager', {google: google_id}]
    user.user_voter:
                class:      UserBundle\Security\UserVoter
                arguments: ['@security.access.decision_manager']
                public:     false
                tags:
                   - { name: security.voter }

    user.datatable.user:
       class: UserBundle\Datatables\UserDatatable
       parent: sg_datatables.datatable.abstract
