intranet_homepage:
    path:     /
    defaults: { _controller: IntranetBundle:Default:index }

###################### Pages #########################

intranet_page_homepage:
    path:     /page
    defaults: { _controller: IntranetBundle:Page:index }

intranet_page_create:
    path:   /page/create
    defaults: { _controller: IntranetBundle:Page:create }

intranet_page_update:
    path:   /page/{id}/update
    defaults: { _controller: IntranetBundle:Page:update }

intranet_page_delete:
    path:   /page/{id}/delete
    defaults: { _controller: IntranetBundle:Page:delete }

intranet_page_view:
    path:   /page/{id}/view
    defaults: { _controller: IntranetBundle:Page:view }

intranet_page_online:
    path:   /page/{id}/online
    defaults: { _controller: IntranetBundle:Page:online }

intranet_page_offline:
    path:   /page/{id}/offline
    defaults: { _controller: IntranetBundle:Page:offline }


###################### News #########################

intranet_news_homepage:
    path:   /news
    defaults: { _controller: IntranetBundle:News:index }

intranet_news_create:
    path:   /news/create
    defaults: { _controller: IntranetBundle:News:create }

intranet_news_update:
    path:   /news/{id}/update
    defaults: { _controller: IntranetBundle:News:update }

intranet_news_delete:
    path:   /news/{id}/delete
    defaults: { _controller: IntranetBundle:News:delete }

intranet_news_view:
    path:   /news/{id}/view
    defaults: { _controller: IntranetBundle:News:view }

intranet_news_online:
    path:   /news/{id}/online
    defaults: { _controller: IntranetBundle:News:online }

intranet_news_offline:
    path:   /news/{id}/offline
    defaults: { _controller: IntranetBundle:News:offline }


###################### Users #########################

intranet_user_homepage:
    path:   /users
    defaults: { _controller: IntranetBundle:User:index }


intranet_user_create:
    path:   /user/create
    defaults: { _controller: IntranetBundle:User:create }
    
intranet_user_update:
    path:   /user/{id}/update
    defaults: { _controller: IntranetBundle:User:update }


intranet_user_delete:
    path:   /user/{id}/delete
    defaults: { _controller: IntranetBundle:User:delete }

intranet_user_view:
    path:   /user/{id}/view
    defaults: { _controller: IntranetBundle:User:view }

intranet_user_enable:
    path:   /user/{id}/online
    defaults: { _controller: IntranetBundle:User:enable }

intranet_user_disable:
    path:   /user/{id}/offline
    defaults: { _controller: IntranetBundle:User:disable }

###################  Avatar ###########################
intranet_user_change_avatar:
    path:       /change-avatar
    defaults:   { _controller: UserBundle:Profile:changeAvatar }

intranet_user_upload_avatar:
    path:       /upload-avatar
    defaults:   { _controller: UserBundle:Profile:uploadAvatar }



###################### CRA #########################

intranet_cra_homepage:
    path:     /cra
    defaults: { _controller: IntranetBundle:UserCRA:index }

intranet_cra_create:
    path:   /cra/create
    defaults: { _controller: IntranetBundle:UserCRA:create }

intranet_cra_update:
    path:   /cra/{id}/update
    defaults: { _controller: IntranetBundle:UserCRA:update }

intranet_cra_delete:
    path:   /cra/{id}/delete
    defaults: { _controller: IntranetBundle:UserCRA:delete }

intranet_cra_view:
    path:   /cra/{id}/view
    defaults: { _controller: IntranetBundle:UserCRA:view }

intranet_cra_online:
    path:   /cra/{id}/online
    defaults: { _controller: IntranetBundle:UserCRA:online }

intranet_cra_offline:
    path:   /cra/{id}/offline
    defaults: { _controller: IntranetBundle:UserCRA:offline }


###################### Expense #########################

intranet_expense_homepage:
    path:     /expense
    defaults: { _controller: IntranetBundle:UserExpense:index }

intranet_expense_create:
    path:   /expense/create
    defaults: { _controller: IntranetBundle:UserExpense:create }

intranet_expense_update:
    path:   /expense/{id}/update
    defaults: { _controller: IntranetBundle:UserExpense:update }

intranet_expense_delete:
    path:   /expense/{id}/delete
    defaults: { _controller: IntranetBundle:UserExpense:delete }

intranet_expense_view:
    path:   /expense/{id}/view
    defaults: { _controller: IntranetBundle:UserExpense:view }

intranet_expense_online:
    path:   /expense/{id}/online
    defaults: { _controller: IntranetBundle:UserExpense:online }

intranet_expense_offline:
    path:   /expense/{id}/offline
    defaults: { _controller: IntranetBundle:UserExpense:offline }

###################### Expense Line #########################

intranet_expense_expense_line_create:
    path:   /expense/{id}/expense_line/create
    defaults: { _controller: IntranetBundle:ExpenseLine:create }

intranet_expense_expense_line_update:
    path:   /expense/{id}/expense_line/{expenseLine_id}/update
    defaults: { _controller: IntranetBundle:ExpenseLine:update }

intranet_expense_expense_line_delete:
    path:   /expense/{id}/expense_line/{expenseLine_id}/delete
    defaults: { _controller: IntranetBundle:ExpenseLine:delete }



###################### CV #########################

intranet_cv_homepage:
    path:     /cv
    defaults: { _controller: IntranetBundle:Cv:index }

intranet_cv_create:
    path:   /cv/create
    defaults: { _controller: IntranetBundle:Cv:create }

intranet_cv_update:
    path:   /cv/{id}/update
    defaults: { _controller: IntranetBundle:Cv:update }

intranet_cv_delete:
    path:   /cv/{id}/delete
    defaults: { _controller: IntranetBundle:Cv:delete }

intranet_cv_view:
    path:   /cv/{id}/view
    defaults: { _controller: IntranetBundle:Cv:view }

intranet_cv_online:
    path:   /cv/{id}/online
    defaults: { _controller: IntranetBundle:Cv:online }

intranet_cv_offline:
    path:   /cv/{id}/offline
    defaults: { _controller: IntranetBundle:Cv:offline }


###################### Vacation #########################

intranet_vacation_homepage:
    path:     /vacation
    defaults: { _controller: IntranetBundle:UserVacation:index }

intranet_vacation_create:
    path:   /vacation/create
    defaults: { _controller: IntranetBundle:UserVacation:create }

intranet_vacation_update:
    path:   /vacation/{id}/update
    defaults: { _controller: IntranetBundle:UserVacation:update }

intranet_vacation_delete:
    path:   /vacation/{id}/delete
    defaults: { _controller: IntranetBundle:UserVacation:delete }

intranet_vacation_view:
    path:   /vacation/{id}/view
    defaults: { _controller: IntranetBundle:UserVacation:view }

intranet_vacation_online:
    path:   /vacation/{id}/online
    defaults: { _controller: IntranetBundle:UserVacation:online }

intranet_vacation_offline:
    path:   /vacation/{id}/offline
    defaults: { _controller: IntranetBundle:UserVacation:offline }


###################### Candidacy #########################

intranet_candidacy_homepage:
    path:     /candidacy
    defaults: { _controller: IntranetBundle:Candidacy:index }

intranet_candidacy_create:
    path:   /candidacy/create
    defaults: { _controller: IntranetBundle:Candidacy:create }

intranet_candidacy_update:
    path:   /candidacy/{id}/update
    defaults: { _controller: IntranetBundle:Candidacy:update }

intranet_candidacy_delete:
    path:   /candidacy/{id}/delete
    defaults: { _controller: IntranetBundle:Candidacy:delete }

intranet_candidacy_view:
    path:   /candidacy/{id}/view
    defaults: { _controller: IntranetBundle:Candidacy:view }

intranet_candidacy_online:
    path:   /candidacy/{id}/online
    defaults: { _controller: IntranetBundle:Candidacy:online }

intranet_candidacy_offline:
    path:   /candidacy/{id}/offline
    defaults: { _controller: IntranetBundle:Candidacy:offline }