intranet_homepage:
    path:     /
    defaults: { _controller: IntranetBundle:Default:index }


###################### Pages #########################

intranet_page_homepage:
    path:     /page
    defaults: { _controller: IntranetBundle:Page:index }

intranet_page_create:
    path:   /page/create
    defaults: { _controller: IntranetBundle:Page:create }

intranet_page_update:
    path:   /page/{page_id}/update
    defaults: { _controller: IntranetBundle:Page:update }

intranet_page_delete:
    path:   /page/{page_id}/delete
    defaults: { _controller: IntranetBundle:Page:delete }

intranet_page_view:
    path:   /page/{page_id}/view
    defaults: { _controller: IntranetBundle:Page:view }

intranet_page_online:
    path:   /page/{page_id}/online
    defaults: { _controller: IntranetBundle:Page:online }

intranet_page_offline:
    path:   /page/{page_id}/offline
    defaults: { _controller: IntranetBundle:Page:offline }


###################### News #########################

intranet_news_homepage:
    path:   /news
    defaults: { _controller: IntranetBundle:News:index }

intranet_news_create:
    path:   /news/create
    defaults: { _controller: IntranetBundle:News:create }

intranet_news_update:
    path:   /news/{news_id}/update
    defaults: { _controller: IntranetBundle:News:update }

intranet_news_delete:
    path:   /news/{news_id}/delete
    defaults: { _controller: IntranetBundle:News:delete }

intranet_news_view:
    path:   /news/{news_id}/view
    defaults: { _controller: IntranetBundle:News:view }

intranet_news_online:
    path:   /news/{news_id}/online
    defaults: { _controller: IntranetBundle:News:online }

intranet_news_offline:
    path:   /news/{news_id}/offline
    defaults: { _controller: IntranetBundle:News:offline }


###################### Users #########################

intranet_user_homepage:
    path:   /users
    defaults: { _controller: IntranetBundle:User:index }

intranet_user_create:
    path:   /users/create
    defaults: { _controller: IntranetBundle:User:create }
    
intranet_user_update:
    path:   /user/{user_id}/update
    defaults: { _controller: IntranetBundle:User:update }

intranet_user_delete:
    path:   /user/{user_id}/delete
    defaults: { _controller: IntranetBundle:User:delete }

intranet_user_view:
    path:   /user/{user_id}/view
    defaults: { _controller: IntranetBundle:User:view }

intranet_user_enable:
    path:   /user/{user_id}/online
    defaults: { _controller: IntranetBundle:User:enable }

intranet_user_disable:
    path:   /user/{user_id}/offline
    defaults: { _controller: IntranetBundle:User:disable }