services:
    intranet.repository.news:
        class: IntranetBundle\Repository\NewsRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:News'

    intranet.repository.page:
            class: IntranetBundle\Repository\PageRepository
            factory: ['@doctrine.orm.entity_manager', 'getRepository']
            arguments:
              - 'IntranetBundle:Page'

    intranet.repository.job:
                class: IntranetBundle\Repository\JobRepository
                factory: ['@doctrine.orm.entity_manager', 'getRepository']
                arguments:
                  - 'IntranetBundle:Job'

    intranet.repository.job_offer:
                    class: IntranetBundle\Repository\JobOfferRepository
                    factory: ['@doctrine.orm.entity_manager', 'getRepository']
                    arguments:
                      - 'IntranetBundle:JobOffer'

    intranet.repository.skill:
                        class: IntranetBundle\Repository\SkillRepository
                        factory: ['@doctrine.orm.entity_manager', 'getRepository']
                        arguments:
                          - 'IntranetBundle:Skill'