services:

    #--------------------------REPOSITORIES-----------------------------
    intranet.repository.news:
        class: IntranetBundle\Repository\NewsRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:News'

    intranet.repository.page:
        class: IntranetBundle\Repository\PageRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:Page'

    intranet.repository.job:
        class: IntranetBundle\Repository\JobRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:Job'

    intranet.repository.job_offer:
        class: IntranetBundle\Repository\JobOfferRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:JobOffer'

    intranet.repository.skill:
        class: IntranetBundle\Repository\SkillRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:Skill'

    intranet.repository.cra:
        class: IntranetBundle\Repository\UserCRARepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:UserCRA'

    intranet.repository.expense:
        class: IntranetBundle\Repository\UserExpenseRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:UserExpense'

    intranet.repository.expense_line:
        class: IntranetBundle\Repository\ExpenseLineRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:ExpenseLine'

    intranet.repository.vacation:
        class: IntranetBundle\Repository\UserVacationRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - 'IntranetBundle:UserVacation'


    #-----------------------MENU---------------------------------------------
    app.menu_builder:
        class: Ipssi\IntranetBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
#        tags:
#            - { name: knp_menu.menu_builder, method: createUserMenu, alias: user }
#            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }

    app.user_menu:
            class: Knp\Menu\MenuItem # the service definition requires setting the class
            factory: ["@app.menu_builder", createUserMenu]
            arguments: ["@security.token_storage"]
            tags:
                - { name: knp_menu.menu, alias: user } # The alias is what is used to retrieve the menu

    app.sidebar_menu:
                class: Knp\Menu\MenuItem # the service definition requires setting the class
                factory: ["@app.menu_builder", createSidebarMenu]
                arguments: ["@security.token_storage"]
                tags:
                    - { name: knp_menu.menu, alias: sidebar } # The alias is what is used to retrieve the menu


    #-----------------------VOTERS---------------------------------------------
    intranet.news_voter:
            class:      Ipssi\IntranetBundle\Security\NewsVoter
            arguments: ['@security.access.decision_manager']
            public:     false
            tags:
               - { name: security.voter }