<?php

namespace Ipssi\IntranetBundle\Repository;

/**
 * ExpenseLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseLineRepository extends \Doctrine\ORM\EntityRepository
{
}
