<?php

namespace Ipssi\IntranetBundle\Repository;

/**
 * ExpenseLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseLineRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $expense_id
     */
    public function findAllLinesForOneExpense($expense_id)
    {
        return $this->createQueryBuilder('expenseLine')
            ->where('expenseLine.user_expense = :user_expense')
            ->setParameter('user_expense', $expense_id)
            ->orderBy('expenseLine.id', 'ASC')
            ->getQuery()->getResult();
    }
}
