<?php

namespace Ipssi\IntranetBundle\Repository;

/**
 * JobOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
