<?php

namespace Ipssi\IntranetBundle\Repository;
use Ipssi\JobBundle\Interfaces\FrontRepositoryInterace;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository implements FrontRepositoryInterace
{

    /**
     * @return Ipssi\IntranetBundle\Entity\News
     */
    public function findAllOnline()
    {
        return $this->findBy(['status' => 1]);
    }


    /**
     * @param $slug
     * @return Ipssi\IntranetBundle\Entity\News
     */
    public function findBySlug($slug)
    {
        return $this->findOneBy(['slug' => $slug]);
    }
}
