<?php

namespace Ipssi\IntranetBundle\Repository;

/**
 * PageTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
