<?php

namespace Ipssi\IntranetBundle\Repository;

/**
 * UserCRARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCRARepository extends \Doctrine\ORM\EntityRepository
{
}
