<?php

namespace Ipssi\IntranetBundle\Repository;

/**
 * UserCVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCVRepository extends \Doctrine\ORM\EntityRepository
{
}
