<?php

namespace Ipssi\IntranetBundle\Repository;

/**
 * VacationResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacationResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
