<?php

namespace Ipssi\IpssiBundle\Repository;

/**
 * ExpenseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
