<?php

namespace Ipssi\IpssiBundle\Repository;

/**
 * NewsCategoriyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsCategoriyRepository extends \Doctrine\ORM\EntityRepository
{
}
