<?php

namespace Ipssi\IpssiBundle\Repository;

/**
 * SkillGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
