<?php

namespace Ipssi\IpssiBundle\Repository;

/**
 * UserCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
