<?php

namespace Ipssi\IpssiBundle\Repository;

/**
 * UserExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserExpenseRepository extends \Doctrine\ORM\EntityRepository
{
}
