<?php

namespace Ipssi\IpssiBundle\Repository;

/**
 * UserVacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVacationRepository extends \Doctrine\ORM\EntityRepository
{
}
