<?php

namespace Ipssi\IpssiBundle\Repository;

/**
 * VacationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
