<?php

namespace Ipssi\IpssiBundle\Repository;

/**
 * VacationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacationRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
