ipssi_homepage:
    path:   /
    defaults:   { _controller: "IpssiBundle:Default:index"}


##### News #####
news_homepage:
    path:   /news
    defaults:   { _controller: "IpssiBundle:News:index" }

news_show:
    path:   /news/{slug}
    defaults:   { _controller: "IpssiBundle:News:show" }


###### File #####
file_upload:
    path:   /file/upload
    defaults:   { _controller: "IpssiBundle:File:upload" }